version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
  cache:
    image: "redis"
    ports:
      - "6379:6379"
  worker:
    image: "celery"
    depends_on:
      - web